# Build and publish Codebreaker Blazor to Azure AppService

trigger:
 branches:
   include:
     - main
 paths:
   include:
   - src/clients/blazor/*
   - src/ui/blazor/CodeBreaker.UI.MudBlazor/*
   - src/ui/blazor/CodeBraker.UI.Shared/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solutionFile: 'src/CodeBreaker.Blazor.sln'

stages:
  - stage: 'Build'
    displayName: 'Build the Blazor app with Mud'
    jobs:
    - job: BuildAndPublishJob
      displayName: 'Build Blazor Mud'
    
      pool:
        vmImage: ubuntu-latest
    
      variables:
        outputDirectory: $(Build.ArtifactStagingDirectory)
    
      steps:
      - script: |
          dotnet build -c $(buildConfiguration) $(solutionFile)
        displayName: 'dotnet build'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(buildConfiguration) --output $(outputDirectory)'
          zipAfterPublish: True
      
      - publish: $(outputDirectory)
        artifact: drop
        displayName: 'publish to artifact pipeline'

  - stage: 'DeployStaging'
    displayName: 'Deploy to Azure AppService'
    dependsOn: 'Build'

    jobs:
    - job: DeployStagingJob
      displayName: 'Deploy to Azure AppService'

      pool:
        vmImage: ubuntu-latest

      steps:
        - download: current
          artifact: drop
          displayName: 'Download pipeline artifact'
        
        - script: ls -al '$(Pipeline/Workspace)/drop'
          displayName: 'ls -al $(Pipeline/Workspace)/drop'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'azuremvpconnection'
            appType: 'webAppLinux'
            WebAppName: 'codebreaker-mud'
            deployToSlotOrASE: true
            ResourceGroupName: 'codebreaker'
            SlotName: 'staging'
            packageForLinux: '$(Pipeline/Workspace)/**/*.zip'
            RuntimeStack: 'DOTNETCORE|7.0'
