# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:  
    include:
    - src/shared/CodeBreaker.Shared

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectDirectory: 'src/shared/CodeBreaker.Shared'
  projectFile: 'src/shared/CodeBreaker.Shared/CodeBreaker.Shared.csproj'
  lib-version: 2.0-beta.1$(Build.BuildNumber)

steps:
- script: |
    echo 'library version: $(lib-version)'
    dotnet build --configuration $(buildConfiguration) $(projectFile)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack -c $(buildConfiguration) $(projectFile)
  displayName: 'dotnet pack'
