# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:  
    include:
    - src/shared/CodeBreaker.Shared

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectDirectory: 'src/shared/CodeBreaker.Shared'

steps:
- script: |
    cd $(projectDirectory)
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
