name: Cosmos data lib

on:

  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/services/common/Codebreaker.Data.Cosmos/**'
    - 'src/Codebreaker.Backend.Cosmos.sln'
    - '.github/workflows/codebreaker-lib-cosmos.yml'
    - '.github/workflows/createnuget-withbuildnumber.yml'
    - '.github/workflows/publishnuget-azuredevops.yml'
    - '.github/workflows/publishnuget-nugetserver.yml'

  # Allow manually trigger 
  workflow_dispatch:    

jobs:
  build:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/createnuget-withbuildnumber.yml@main
    with:
      version-suffix: beta.
      version-number: ${{ github.run_number }}
      version-offset: 10
      solutionfile-path: src/Codebreaker.Backend.Cosmos.sln
      projectfile-path: src/services/common/Codebreaker.Data.Cosmos/Codebreaker.Data.Cosmos.csproj
      dotnet-version: '8.0.x'
      artifact-name: codebreaker-cosmos
      branch-name: main

  publishdevops:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-azuredevops.yml@main
    needs: build
    with:
      artifact-name: codebreaker-cosmos
    secrets: inherit

  publishnuget:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-nugetserver.yml@main
    needs: publishdevops
    with:
      artifact-name: codebreaker-cosmos
    secrets: inherit
