name: Publish to Azure

on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches: 
      [ main ]
    paths:
    - 'src/services/bot/**'
    - 'src/services/gameapis/**'
    - 'src/services/gateway/**'
    - 'src/services/host/**'
    - 'src/services/live/**'
    - 'src/services/ranking/**'
    - 'src/services/user/**'

# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config`
# check support with multiple environments: https://github.com/Azure/azure-dev/issues/2373
# Workaround:
# https://github.com/jasontaylordev/todo-aspnetcore-csharp-sqlite/blob/main/OPTIONAL_FEATURES.md

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

# https://github.com/Azure/azure-dev/issues/4157 - update to azd way after issue is resolved          
      - name: Setup .NET Aspire
        run: dotnet workload install aspire

      - name: Package Application
        run: azd package --output-path ./dist/codebreaker.zip --environment NON
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./dist/codebreaker.zip
          if-no-files-found: error
        
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [build]
    with:
      AZURE_ENV_NAME: codebreakertest

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [deploy-test]
    with:
      AZURE_ENV_NAME: codebreakerprod