name: Backend models lib

on:

  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/services/gameapi/Codebreaker.GameAPIs.Models/**'
    - 'src/Codebreaker.Analyzers.sln'
    - '.github/workflows/codebreaker-lib-backendmodels.yml'
    - '.github/workflows/createnuget-withbuildnumber.yml'
    - '.github/workflows/publishnuget-azuredevops.yml'
    - '.github/workflows/publishnuget-nugetserver.yml'

  # Allow manually trigger 
  workflow_dispatch:    

jobs:
  build:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/createnuget-withbuildnumber.yml@main
    with:
      version-suffix: beta.
      version-number: ${{ github.run_number }}
      version-offset: 10
      solutionfile-path: src/Codebreaker.GameApis.sln
      projectfile-path: src/services/gameapi/Codebreaker.GameAPIs.Models/Codebreaker.GameApis.Models.csproj
      dotnet-version: '8.0.x'
      artifact-name: codebreaker-backendmodels
      branch-name: main

  publishdevops:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-azuredevops.yml@main
    needs: build
    with:
      artifact-name: codebreaker-backend-models
    secrets: inherit

  publishnuget:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-nugetserver.yml@main
    needs: publishdevops
    with:
      artifact-name: codebreaker-backend-models
    secrets: inherit
